export enum FoodCategory {
  FRUITS = 'FRUITS',
  VEGETABLES = 'VEGETABLES',
  DAIRY = 'DAIRY',
  BAKERY = 'BAKERY',
  MEAT = 'MEAT',
  FISH = 'FISH',
  CANNED_GOODS = 'CANNED_GOODS',
  DRY_GOODS = 'DRY_GOODS',
  FROZEN = 'FROZEN',
  BEVERAGES = 'BEVERAGES',
  SNACKS = 'SNACKS',
  OTHER = 'OTHER',
}
